spring:
  jpa:
    hibernate.ddl-auto: create-drop
    database: HSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
  datasource:
    driverClassName: org.hsqldb.jdbcDriver
    url: jdbc:hsqldb:mem:test-db
    username: sa
    password: sa
  flyway:
    enabled: false